language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcre

before_script:
  - "./bootstrap"

script:
  - "./travis.sh"

notifications:
  email: false
