language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libev-dev
  - sudo apt-get install -qq libcunit1-dev

before_script:
  - "./bootstrap"
  - "./configure --with-test"

script:
  - "make check"

notifications:
  email: false
